apiVersion: autoscaling/v1  
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-minio-staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-minio-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-minio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-minio
  template:
    metadata:
      labels:
        app: nginx-minio
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "150m"
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-minio-config